/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */

export type ChatReplyMode = (typeof ChatReplyMode)[keyof typeof ChatReplyMode];

export const ChatReplyMode = {
  llm: "llm",
  rules: "rules",
} as const;
