/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */
import type { ChatReplyMode } from "./chatReplyMode";
import type { Cite } from "./cite";

export interface ChatReply {
  cite: string;
  paras: string[];
  cites?: Cite[];
  contract_id?: number | null;
  mode?: ChatReplyMode;
  degraded?: boolean;
}
