/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 可点击的条款引用：条号 + 条款 id，前端据此打开抽屉并高亮
 */
export interface Cite {
  clause_no: number;
  clause_id: number;
  title?: string | null;
}
