/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */
import type { RiskLevel } from "./riskLevel";

/**
 * 抽屉里一条条款可能命中多条规则（如押金条款），必须全列出来而不是只留最后一条
 */
export interface ClauseRisk {
  id: number;
  level: RiskLevel;
  rule_id: string;
  title: string;
  reason: string;
  suggestion: string;
  negotiation_script?: string | null;
}
