/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */
import type { ClauseRisk } from "./clauseRisk";

export interface ClauseView {
  id: number;
  clause_no: number | null;
  clause_type: string;
  title: string;
  raw_text: string;
  is_risk?: boolean;
  risks?: ClauseRisk[];
}
