/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */
import type { ContractStatus } from "./contractStatus";

export interface ContractOut {
  id: number;
  filename: string | null;
  source_type: string;
  status: ContractStatus;
  storage_key?: string | null;
  health_score: number | null;
  error: string | null;
  created_at: string;
}
