/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */

export interface ContractCreate {
  /**
   * 合同全文（粘贴）
   * @minLength 50
   * @maxLength 200000
   */
  text: string;
  filename?: string | null;
}
