/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */
import type { ClauseView } from "./clauseView";

export interface ContractTextView {
  contract_id: number;
  filename: string | null;
  clauses: ClauseView[];
}
