/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */

export type RiskLevel = (typeof RiskLevel)[keyof typeof RiskLevel];

export const RiskLevel = {
  high: "high",
  medium: "medium",
  low: "low",
} as const;
