/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */
import type { RiskLevel } from "./riskLevel";

export interface RiskView {
  id: number;
  level: RiskLevel;
  clause_id: number;
  clause_no?: number | null;
  clause_title?: string | null;
  rule_id: string;
  title: string;
  reason: string;
  suggestion: string;
  negotiation_script?: string | null;
}
