/**
 * Generated by orval 🍺
 * Do not edit manually.
 * RentGraph API
 * OpenAPI spec version: 0.1.0
 */
import type { RisksSummaryCounts } from "./risksSummaryCounts";
import type { RiskView } from "./riskView";

export interface RisksSummary {
  contract_id: number;
  filename?: string | null;
  health_score: number | null;
  counts: RisksSummaryCounts;
  risks: RiskView[];
}
